[project]
name = "stockdice-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "polars>=1.32.0",
    "stockdice",
]

[tool.uv.workspace]
members = [
    "shared-library",
]

[tool.uv.sources]
stockdice = { workspace = true }

[dependency-groups]
dev = [
    "ipython>=9.4.0",
    "ruff>=0.12.7",
]
